### ISSUE TITLE
Enable check_untyped_defs mypy option

### ISSUE THREAD

**Issue by kevinsung** [qiskit-community/ffsim#124]
Many test functions aren't being type checked because they aren't annotated. To make sure they are checked, add
```toml
[tool.mypy]
check_untyped_defs = true
```
in `pyproject.toml`.
